services:
  web:
    build:
      context: .
      target: web
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      migrate:
        condition: service_completed_successfully

  worker:
    build:
      context: .
      target: worker
    env_file: .env
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    build:
      context: .
      target: migrate
    env_file: .env
